version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "9411:9411"
      - "16686:16686"
    expose:
      - 16686
      - 9411
      - 6831
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
